### ISSUE TITLE
Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by garret** [ethowitz/polybar-protonvpn#1]
Hi, I wanted to use your module but I cannot get it to work. After copying your script (renamed protonvpn) and chmod it, if I launch it I get this error: 
```
➜  ~ .config/polybar/scripts/protonvpn
.config/polybar/scripts/protonvpn: 4: Syntax error: redirection unexpected
➜  ~
```
The command `protonvpn s` seems to work as I get information: 
```
➜  ~ protonvpn s
Status:     Disconnected
IP:         X.X.X.X
ISP:        XXX
➜  ~
```
Do you know what I am doing wrong?

**Comment by ethowitz** [comment]
@garret Hmm what shell are you using?

**Comment by garret** [comment]
@ethowitz I am using zsh

**Comment by ethowitz** [comment]
Ah, it looks like the `<<<` operator isn't available in some shells, and specifying `#!/bin/sh` will use the default shell for your operating system. Can you try changing the first line of the script to `#!/bin/zsh`?

**Comment by garret** [comment]
I reverted to bash just to see if the script works and I get the same error unfortunately: 
```
[garret@void ~]$ .config/polybar/scripts/protonvpn
.config/polybar/scripts/protonvpn: 4: Syntax error: redirection unexpected
[garret@void ~]$
```

**Comment by ethowitz** [comment]
I think running the script directly from the command line will always use the shell specified in the shebang at the top of the script. Can you try running `zsh .config/polybar/scripts/protonvpn`?

**Comment by garret** [comment]
Giving that command seems I get the correct output (don't have protonvpn active at the moment): 
```
[garret@void ~]$ zsh .config/polybar/scripts/protonvpn

[garret@void ~]$
```

**Comment by ethowitz** [comment]
Yeah, if you replace the first line of the script (the `#!/bin/sh`) with `#!/bin/zsh`, that should do the trick I think

**Comment by garret** [comment]
Ok thanks, yes I can see it works. So actually `zsh` is a needed dependence for this module to work? 
For the icons (like the open lock) to be visualized I should use a nerdfont to see them on my bar?

**Comment by ethowitz** [comment]
Any shell that is backwards compatible with bash should work (which is why zsh works). I've updated the script in this repository to specify `#!/bin/bash` instead of `#!/bin/sh`. And the icon I included is part of [Font Awesome](https://fontawesome.com/); if you're using Arch, you can grab it via `# pacman -S ttf-font-awesome`. You could also replace the icon in the script with an icon from a font of your choosing if you want.

Sorry for the confusion!
